services:
  pg:
    image: 'bitnami/postgresql:latest'
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: upload_api
    ports:
      - 5432:5432
    volumes:
      - './docker:/docker-entrypoint-initdb.d'